apiVersion: v1
kind: Pod
metadata:
  name: netology-web
  labels:
     app: webn
spec:
  containers:
  - name: netalogy-web
    image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2

---
apiVersion: v1
kind: Service
metadata:
  name: netology-svc
  labels:
     app: webn

spec:
  selector:
      app: webn
  ports:
    - protocol: TCP
      port: 8080
